#!/usr/bin/zsh

if [[ "$#" -eq 0 ]]
then
	echo "    bp retrieves a file list from beets (beet) and calls"
	echo "    rplay to remotely play them. bp plays the tracks in"
	echo "    the order beet returns them."
	echo ""
	echo "    Usage:"
	echo "        bp [options] <beet search criteria>"
	echo ""
	echo "    Options (must be the first option/s on the command line):"
	echo "        --shuffle    will play the tracks in random order."
	echo "        --show       will print the paths to the tracks "
	echo "                     before playing them."
	echo "        --show-each  will be passed to rplay and will cause"
	echo "                     rplay to display the name of each track"
	echo "                     as it is played. This will bypass the"
	echo "                     default gapless play."
	echo ""
	echo "    bp will call beet with the options \"-f '\$path'\". You will"
	echo "    provide the search criteria to find the tracks desired."
	echo "    For example, to play all tracks from disc 1 of an album"
	echo "    named 'Namaste', you might enter:"
	echo "        bp album:Namaste disc:01 "
	echo ""
	echo "    Default options for beet can be set in the environment"
	echo "    variable \$BEETDEFAULTS. These will be applied to all"
	echo "    uses of bp. \$BEETDEFAULTS should only be beets 'match'"
	echo "    options (e.g. \"genre:rock\" or \"^genre:chirstmas\","
	echo "    other options may have unexpected behavior."
	echo ""
	echo "    All the command line options provided to bp (except bp's "
	echo "    own options) will be passed unchanged to the beet command."
	echo "    As such, no options will be passed to rplay."
	echo "    To provide options to rplay use the environment"
	echo "    variable RPLAYPARAMETERS (see 'rplay -h' for details)."
	echo ""
	exit
fi

tracks=()
shuffle=
show=
showeach=

while [[ "${1}" =~ "--shuffle|--show|--show-each" ]]
do
	if [[ "${1}" == "--shuffle" ]]
	then
		shuffle="--shuffle"
	elif [[ "${1}" == "--show" ]]
	then
		show=yes
	elif [[ "${1}" == "--show-each" ]]
	then
		showeach="--show-each"
	fi
	shift 1
done

BP=()
eval "BP=($BEETDEFAULTS)"

beet list -f '$path' "$@" "${BP}" | while read LINE
do
	tracks+=( "${LINE}" )
	if [[ -n "${show}" ]]
	then
		echo "${LINE}"
	fi
done

if [[ ${#tracks} -gt 0 ]]
then
	rplay ${shuffle} ${shuffle} "${tracks[@]}"
else
	echo "No matches to "$@""
fi
