#!/usr/bin/zsh


while [[ "$1" ]]
do
	local filename="$1"

	local pmedia=$(exiftool "$filename" | grep PMEDIA)
	if [[  "$pmedia" ]]
	then
		printf "PMEDIA %s\n" "$filename"

		printf "%s\n" "$pmedia" | while read LINE
		do
			local field=$(echo "\t$LINE" | awk '{print $1}')
			print "\tRemoving $field"
			metaflac "--remove-tag=${field:u}" "$filename"
		done
	fi
	shift
done