#!/usr/bin/zsh

function usage
{
	print 'Usage:'
	print '	yf <resolution id> <url>'
	print '	Will download <url> at the resolution specified by <resolution id>'
	print '	<url> must begin with http:// or https://'
	print '	order of parameters does not matter.'
	print ' OR'
	print '	yf <url>'
	print "	Will lookup which resolution options are available for <url>"
	print
	exit -1
}

if [[ "$#" -eq 2 ]]
then
	url=
	resid=
	if [[ "$1" =~ 'http[s]?://' ]]
	then
		echo "1 http or https"
		url="$1"
		resid="$2"
	elif [[ "$2" =~ 'http[s]?://' ]]
	then
		echo "2 http or https"
		url="$2"
		resid="$1"
	else
		usage
	fi
	echo "yt-dlp -f $resid $url"
	yt-dlp -f "$resid" "$url"
elif [[ "$#" -eq 1 ]]
then
	yt-dlp -F "$1"
else
	usage
fi
